frr version 10.0
frr defaults traditional
hostname router1
log stdout
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.1.1/24
 ip ospf area 0.0.0.0
!
interface eth2
 ip address 10.0.12.1/30
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth3
 ip address 10.0.100.2/30
!
router ospf
 ospf router-id 1.1.1.1
 passive-interface eth1
 network 10.0.1.0/24 area 0.0.0.0
 network 10.0.12.0/30 area 0.0.0.0
 default-information originate
!
ip route 0.0.0.0/0 10.0.100.1
!
line vty
!
